### PR TITLE
Label Scan Plan

### LINKED ISSUE #20: Label Scanning Plan Widget
**Is your feature request related to a problem? Please describe.**
Scan plan widget unclear what it does

**Describe the solution you'd like**
Add label to indicate use of function

### PR DESCRIPTION
**Pull request by micahwoodard**
fixes #20 
- labels scan plan widget using QGroupbox
- Uses QStackedWidget to simplify toggling view of z widget

### CODE REVIEW

**Comment by micahwoodard** [comment]
This is what it looks like. I can change Tile Volume to anything though to make it more clear

https://github.com/AllenNeuralDynamics/view/assets/110491290/1c014faa-8620-4144-8469-f9d2e5b4d4cc

**Review by adamkglaser — CHANGES_REQUESTED** [review]
Hmm for some reason I can't reproduce this working on my windows workstation with the simulated instrument in the view repo? Can you confirm that the current committed version works as in your video?

**Comment by micahwoodard** [comment]
Is the Tile Volume label not showing up or is the tile not switching when you click on it? If the tile isn't switching maybe it's because you have the apply all checkbox checked. The switching behavior only happens if you can edit individual tiles. Maybe I should change the Tile Volume label so if you have apply all checked, then the label shows no row, column and if you have apply all unchecked that's when it displays row, column

**Comment by adamkglaser** [comment]
Ah I see. It is working correctly when the box is not checked. Yes I think it might remove a little bit of confusion to have the default not say (0,0). Something like "All tiles" when the box is checked would be helpful. Otherwise OK to merge.

**Pull request merged**
