### PR TITLE
Align parameters horizontally

### LINKED ISSUE #12: Orient parameters horizontally
**Is your feature request related to a problem? Please describe.**
Instrument view is cluttered.

**Describe the solution you'd like**
It would help if widgets like stage and lasers were stacked vertically and parameters extended horizontally 

**Acceptance Criteria**

- [ ] stack widgets vertically
- [ ] extend parameters horizontally
- [ ] have labels of parameters at top of columns

### LINKED ISSUE #13: Move Channels to left
**Is your feature request related to a problem? Please describe.**
Move aesthetically pleasing to have channels on the left 

**Describe the solution you'd like**
Move aesthetically pleasing to have channels on the left 

**Acceptance Criteria**

- [ ] move channels to left of instrument view

### LINKED ISSUE #15: Fix unit labels in property names
**Is your feature request related to a problem? Please describe.**
Units in names are properties are mangled 

**Describe the solution you'd like**
If a unit is in name, put in brackets and correctly capitalize

**Acceptance Criteria**

- [ ] modify label_maker to be able to recognize unit
- [ ] put in brackets 
- [ ] correctly capitalize

### PR DESCRIPTION
**Pull request by micahwoodard**
fixes #12 
fixes #13 

- align lasers horizontally
- add frame around lasers
- align stage horizontally
- move channels to left
- better assign QSizePolicy

### CODE REVIEW

**Comment by adamkglaser** [comment]
i'll take a look at this this evening or tomorrow (hopefully on a windows PC and not my mac)

**Comment by micahwoodard** [comment]
> i'll take a look at this this evening or tomorrow (hopefully on a windows PC and not my mac)

Okay I don't think it's finished just yet and just as a warning it's not exactly as you described in the meeting. I think I'm struggling with the stage widgets and how to organize them so it wouldn't break the code if you had a slightly different widget. Also it's confusing because the stage widget names and position dictionary is referencing the hardware axis not the instrument axis but I don't see the hardware or instrument axis exposed in the stage base class so I don't know if it's safe to assume that every stage driver will have that. Also, the property stage_position_mm returns a dictionary which changes how the position widget looks, so should I also assume that every stage driver will return a dictionary when asking for the position?

**Comment by adamkglaser** [comment]
> > i'll take a look at this this evening or tomorrow (hopefully on a windows PC and not my mac)
> 
> Okay I don't think it's finished just yet and just as a warning it's not exactly as you described in the meeting. I think I'm struggling with the stage widgets and how to organize them so it wouldn't break the code if you had a slightly different widget. Also it's confusing because the stage widget names and position dictionary is referencing the hardware axis not the instrument axis but I don't see the hardware or instrument axis exposed in the stage base class so I don't know if it's safe to assume that every stage driver will have that. Also, the property stage_position_mm returns a dictionary which changes how the position widget looks, so should I also assume that every stage driver will return a dictionary when asking for the position?

ack wow i did not realize the stage driver is a bit of a mess. i think we need to

- [ ] expose instrument/hardware axis so that they are accessible outside of the driver for the GUI
- [ ] change position_mm to return a float and not a dict, where the GUI grabs instrument axis for the letter label

also if it is easier on the Qt side, having an indicator table as the widget might be much more compact and organized? for example it is a waste of space to show position_mm over and over for each axis.

image

**Comment by micahwoodard** [comment]
QTables are kind of a headache so that might be a longer refactor if that is what we want to go for. But I agree with the other stuff you said.

**Comment by adamkglaser** [comment]
that sounds good. but a compact indicator layout like a table would be good. and for the gui yaml configuration the specified properties could be axis specific, or just for all axes (either i think is fine). in a way to keep a consistent sizing perhaps all columns are always shown.

**Comment by micahwoodard** [comment]
> that sounds good. but a compact indicator layout like a table would be good. and for the gui yaml configuration the specified properties could be axis specific, or just for all axes (either i think is fine). in a way to keep a consistent sizing perhaps all columns are always shown.

I might push back a little on this exact refactor because it involves assuming a lot about the stage widgets and effectively shuts the door for people being able to use different widgets for the stages which kinda goes against what I've been trying to do. Happy to be convinced though if you're in later today?

**Comment by adamkglaser** [comment]
That sounds good. How about we chat after the CZI meeting?
________________________________

**Comment by micahwoodard** [comment]
image

@adamkglaser  this is how the stage widgets will look if they all are not in advanced simulator mode. The minimum width is restricted by the napari layer controls, so it can't get any narrower. Let me know what you think and if you would prefer with out the boxes, different labeling, or horizontal rather that vertical

**Comment by micahwoodard** [comment]
image
Here it is if you are in advanced user mode for the x axis

**Comment by adamkglaser** [comment]
> image
> 
> @adamkglaser this is how the stage widgets will look now if they all are not in advanced simulator mode and run with changes I made in the branch feat-22-reconfigure-stage-base in voxel. The minimum width is restricted by the napari layer controls, so it can't get any narrower. Let me know what you think and if you would prefer with out the outline boxes, different labeling, or horizontal rather that vertical

this looks good to me. minor thing is that i know this is a property with no setter (so just indicator) but is it possible to change the gray to something lighter or even white? for other indicators the dulled gray is OK but for this one the user would be constantly looking at the XYZ position and making it more visible would be helpful.

**Comment by micahwoodard** [comment]
Yeah I agree. I will change text color and then merge

**Pull request merged**
