### PR TITLE
Units in Label 

### LINKED ISSUE #15: Fix unit labels in property names
**Is your feature request related to a problem? Please describe.**
Units in names are properties are mangled 

**Describe the solution you'd like**
If a unit is in name, put in brackets and correctly capitalize

**Acceptance Criteria**

- [ ] modify label_maker to be able to recognize unit
- [ ] put in brackets 
- [ ] correctly capitalize

### LINKED ISSUE #19: Remove underscore and brackets for channel table settings
**Describe the solution you'd like**
Remove underscore and brackets for channel table settings. Could possibly use fix for #15 . Also add um to step size (constant for all scans)

### PR DESCRIPTION
**Pull request by micahwoodard**
fixes #15 
fixes #19 
- label_maker identifies common units if in name
- channel plan columns use label_maker for headers
-  table headers include units

### CODE REVIEW

**Comment by micahwoodard** [comment]
Can't handle speeds for example speed_mm_s. It will be parsed as speed [mm] [s]. Might want to change in the variable name or think of a more clever way to parse? I can see using regular expressions to parse the name may fix this

**Comment by adamkglaser** [comment]
rather than trying to parse it from the property name, which i see that we don't explicitly specify whether it is a double unit that is multiplicative or division based. we can instead handle this by pulling the unit as a delineated property? the delineated unit property will show up everywhere in the UI, and the property name itself is just to remind ourselves within the code what the units are for the different properties?

**Comment by micahwoodard** [comment]
> rather than trying to parse it from the property name, which i see that we don't explicitly specify whether it is a double unit that is multiplicative or division based. we can instead handle this by pulling the unit as a delineated property? the delineated unit property will show up everywhere in the UI, and the property name itself is just to remind ourselves within the code what the units are for the different properties?

yeah I'm just thinking for properties or drivers that don't use the delinated property (which I think is realistic?), parsing the name would also be good to have. I can scrap this pr if you don't think it would be useful to do both though. And then this issue would be blocked until units are added to deliminated_property

**Comment by adamkglaser** [comment]
> > rather than trying to parse it from the property name, which i see that we don't explicitly specify whether it is a double unit that is multiplicative or division based. we can instead handle this by pulling the unit as a delineated property? the delineated unit property will show up everywhere in the UI, and the property name itself is just to remind ourselves within the code what the units are for the different properties?
> 
> yeah I'm just thinking for properties or drivers that don't use the delinated property (which I think is realistic?), parsing the name would also be good to have. I can scrap this pr if you don't think it would be useful to do both though. And then this issue would be blocked until units are added to deliminated_property

i think the two options would be to 1) enforce that the delineated property always has to be used with units in the drivers? this doesn't seem too unreasonable? or 2) we would have to have a lookup table that maps property unit formatting to GUI unit formatting. like mm_s -> [mm/s]. but for this we'd have to have a way to encode whether it is multiplied or divided units. although multiplied units seems rare (we don't have any now). a unit mms we could map in the lookup table to [mm x s] or we could change the property naming convention to be more explicit. mm_x_s for multiplication. mm_s or mm__s for division? #1 seems more general and less hacky, and is just an opinionated requirement that has to be mentioned in documentation?

**Comment by micahwoodard** [comment]
> 
> i think the two options would be to 1) enforce that the delineated property always has to be used with units in the drivers? this doesn't seem too unreasonable? or 2) we would have to have a lookup table that maps property unit formatting to GUI unit formatting. like mm_s -> [mm/s]. but for this we'd have to have a way to encode whether it is multiplied or divided units. although multiplied units seems rare (we don't have any now). a unit mms we could map in the lookup table to [mm x s] or we could change the property naming convention to be more explicit. mm_x_s for multiplication. mm_s or mm__s for division? #1 seems more general and less hacky, and is just an opinionated requirement that has to be mentioned in documentation?

I think we could do both 1) and 2) and accommodate users who don't want to use deliminated property and just want to store info in the property name. But if you want to go one way or the other that makes sense too. I am almost convinced that we should just use the deliminated property just so things wouldn't be parsed incorrectly

I think for option 2) yeah what you said you'd have to make the unit name more specific in the property and then be clever in the unit look up table. I did this quickly and didn't think about multiplied or divided units so I didn't take the time to use a regular expression but I can rework it to parse out if that's the route we want to go. But also if we go with doing both we can just leave it and say if you have a more complex unit, use deliminated property. 

I'll leave it up to what you think is best because I can see pros and cons either way we do it

**Comment by adamkglaser** [comment]
i think keeping things open is a good idea. #1 takes precedence, but if not defined, #2 is a backup. almost like the "base" unit label maker.

**Pull request merged**
