### PR TITLE
Refactor filter wheel 

### LINKED ISSUE #5: Upgrade Filter Wheel
**Is your feature request related to a problem? Please describe.**
Filter wheel could be more accurate to reality and more aesthetically pleasing. This issue may need to be several smaller issues

**Describe the solution you'd like**
Instead of moving small blue circle, move text and change circle color. This is more realistic. Also, get rid of text so the widget will scale better. 

**Acceptance Criteria**

- [ ] Remove text
- [ ] Change small circle color upon changing filter wheel 
- [ ] Small circle is now stationary and should be locked in top notch position

### PR DESCRIPTION
**Pull request by micahwoodard**
fixes #5 
- added circles for all filters
- colors now a kw argument
- filters now move to notch at top

### CODE REVIEW

**Comment by micahwoodard** [comment]
Users can either click on desired filter or select which filter in combo box

https://github.com/user-attachments/assets/54c8088d-6e4c-4aa7-863c-ae728983c204

**Comment by micahwoodard** [comment]
@adamkglaser does it make more sense to have the filter names inside the filters instead of the indexes? Not a huge difference either way

**Comment by micahwoodard** [comment]
Actually I think it makes the most sense to have the numbers. The text objects don't scale with the widget size so I think numbers are more legible with how small the filterwheel widget usually gets sized to.

**Comment by adamkglaser** [comment]
Agreed thats why I specified numbers not the full names in the original issue. This looks good to me. And just checking, the colors dict would be defined in the GUI YAML for an actual system?

**Review by adamkglaser — APPROVED** [review]

**Pull request merged**
