### PR TITLE
changes to volume model widget aesthetics

### PR DESCRIPTION
**Pull request by adamkglaser**

### CODE REVIEW

**Comment by micahwoodard** [comment]
@adamkglaser I made some changes to your version but maintained functionality. Mainly just shuffled things around and added arguments to the init but two big things I did were
- Made a class called GLPathItem that does all the arrow math internally 
- Am using a subclass of GLBarGraphItem to make shaded boxes instead of drawing each face. I thought this approach made the code more readable and also easier to maintain in the future. Let me know what you think

**Comment by adamkglaser** [comment]
> @adamkglaser I made some changes to your version but maintained functionality. Mainly just shuffled things around and added arguments to the init but two big things I did were
> 
> * Made a class called GLPathItem that does all the arrow math internally
> * Am using a subclass of GLBarGraphItem to make shaded boxes instead of drawing each face. I thought this approach made the code more readable and also easier to maintain in the future. Let me know what you think

This all looks great to me. One note about the GLBarGraphItem vs drawing the faces individually. The additive blending means that in XY view (since we have no Z tiles) the opacity is as expected. In XZ and YZ there are more "added" faces depending on the number of tiles in Y or X respectively, so the opacity goes up linearly. I tried the other modes like translucent but in my testing additive by far looked the best and as I envisioned things in my mind. To get around this, I rendered the XZ faces with tile_opacity/y_tiles and YZ faces with tile_opacity/x_tiles. I'm not sure if that is possible with the BarGraphItem, to render faces with different opacities?

Also this is something that I may have broken, I don't think it is from your changes. But the clicking FOV and moving around to tiles seems incorrect now... not sure if its an arithmetic error somewhere, or due to changing to the ortho view. Hopefully this one is quick to fix.

**Comment by micahwoodard** [comment]
For the opacity, I'm not sure if we can render the faces with different opacity but I can look into adding to GLQBarGraphItem's paint function. To me, the fact that opacity increases with more rows/columns is a useful visual implication and not a detriment, but I also see your point. 

For the moving of fov, I will look into it. It probably has to do with the fact that the constant 1200 isn't being applied here.

**Comment by adamkglaser** [comment]
Agreed for the opacity. I wouldn't sink a ton of time into this and looking at the paint function. But obviously debugging the moving fov is important. Hopefully its just something to do with the 1200 factor missing in another section of the code.

**Comment by micahwoodard** [comment]
Maybe look at what I've done here? I think I'm doing something a little off because it's not behaving exactly how I'd expect but it is scaling the opacity somewhat based on row and columns. You might be a better person to debug, I think you're better at opengl than me

**Comment by adamkglaser** [comment]
i'll take a look

**Comment by micahwoodard** [comment]
Okay cool. I'm getting an really  error where when I run the volume_widget_example, everything is fine but when I run simulated-view I get an opengl error saying "Error while drawing item <view.widgets.miscellaneous_widgets.gl_shaded_box_item.GLShadedBoxItem object at 0x0000022A0494FEB0>.". I think it has to do with the opengl contexts, not the widget but I'm still debugging

**Comment by micahwoodard** [comment]
Bugs fixed so will merge

**Pull request merged**
