### PR TITLE
Fixing bugs/visuals

### PR DESCRIPTION
**Pull request by micahwoodard**
Fixed some bugs/visuals in gui including 

- ampersand saving in yaml
- saving instrument yaml instead of gui
- joystick widget having awkward text box
- base device widget drop downs
- daq decimal place set to 4
- laser slider set when released

### CODE REVIEW

**Comment by micahwoodard** [comment]
Still have a couple to change like the exposed branches init argument and gui_yaml check but this addresses a lot of what we talked about friday

**Comment by adamkglaser** [comment]
@micahwoodard  sounds good. Do you want to make those a separate PR or are you going to add those into this one?

**Comment by micahwoodard** [comment]
probably a separate pull request since I think those might take longer to implement

**Comment by adamkglaser** [comment]
Sounds good. @micahwoodard  the visuals seems fixed, and we can test the YAML fixes later this morning.

However, on this branch and develop live streaming seems to be broken. It is OK on main. Not sure what changed... any chance you can debug this morning? Here is the error:

Traceback (most recent call last):
  File "C:\Users\svc_aind_imaging\AppData\Local\miniconda3\envs\exa-spim\Lib\site-packages\superqt\utils\_qthreading.py", line 613, in reraise
    raise e
  File "C:\Users\svc_aind_imaging\AppData\Local\miniconda3\envs\exa-spim\Lib\site-packages\superqt\utils\_qthreading.py", line 175, in run
    result = self.work()
             ^^^^^^^^^^^
  File "C:\Users\svc_aind_imaging\AppData\Local\miniconda3\envs\exa-spim\Lib\site-packages\superqt\utils\_qthreading.py", line 440, in work
    output = self._gen.send(_input)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_imaging\Documents\GitHub\view\src\view\instrument_view.py", line 394, in grab_frames
    yield self.instrument.cameras[camera_name].grab_frame(), camera_name
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_imaging\AppData\Local\miniconda3\envs\exa-spim\Lib\site-packages\voxel\instruments\instrument.py", line 197, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_imaging\AppData\Local\miniconda3\envs\exa-spim\Lib\site-packages\voxel\devices\camera\vieworks_egrabber.py", line 353, in grab_frame
    with Buffer(self.grabber, timeout=timeout_ms) as buffer:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_imaging\AppData\Local\miniconda3\envs\exa-spim\Lib\site-packages\egrabber\egrabber.py", line 2142, in __init__
    self.new_buffer_data = grabber.pop(timeout)
                           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_imaging\AppData\Local\miniconda3\envs\exa-spim\Lib\site-packages\egrabber\egrabber.py", line 1228, in pop
    cE.Eur_EGrabber_CallbackOnDemand_pop__from__uint64_t(
  File "C:\Users\svc_aind_imaging\AppData\Local\miniconda3\envs\exa-spim\Lib\site-packages\egrabber\generated\errors.py", line 29, in __call__
    raise TimeoutException()
egrabber.generated.errors.TimeoutException: GC_ERR_TIMEOUT
Traceback (most recent call last):
  File "C:\Users\svc_aind_imaging\Documents\GitHub\view\src\view\instrument_view.py", line 344, in <lambda>
    self.grab_frames_worker.finished.connect(lambda: self.dismantle_live(camera_name))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_imaging\Documents\GitHub\view\src\view\instrument_view.py", line 380, in dismantle_live
    for laser_name in self.channels[self.livestream_channel].get('lasers', []):
                      ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_imaging\AppData\Local\miniconda3\envs\exa-spim\Lib\site-packages\ruamel\yaml\comments.py", line 853, in __getitem__
    return ordereddict.__getitem__(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: None

**Comment by micahwoodard** [comment]
yeah fixing [here ](https://github.com/AllenNeuralDynamics/view/pull/93)

**Pull request merged**
