### PR TITLE
Reformatted widgets in camera

### LINKED ISSUE #14: Reorganize Camera Widget
**Is your feature request related to a problem? Please describe.**
Camera widget is cluttered 

**Describe the solution you'd like**
Reorganize widgets so widgets are side by side like  sensor height/ width, binning/pixel type, snapshot/ livebutton 

**Acceptance Criteria**

- [ ] sensor height/ width are side by side
- [ ] binning/pixel type side by side
- [ ] snapshot/ livebutton side by side

### LINKED ISSUE #25: Warning for QLayouts
**Is your feature request related to a problem? Please describe.**
When camera gui is initializing, vispy and QLayout warnings pop up like "WARNING:vispy | QLayout::addChildLayout: layout QHBoxLayout "" already has a parent". Pretty sure it's coming from reorganizing the roi widget

**Describe the solution you'd like**
Reorganize roi layout so warnings do not occur

**Acceptance Criteria**

- [ ] eliminate warnings when camera gui is eliminated

### PR DESCRIPTION
**Pull request by micahwoodard**
fixes #25 
fixes #14 
- if in advanced user mode, camera widgets are grouped to take up less space 
- running camera_example.py in the examples folder will give a good visual of how it is regrouped

### CODE REVIEW

**Comment by adamkglaser** [comment]
this looks great, very minor tweaks

- [ ] restack the horizontal sections as live/snapshot, binning/pixel type, exposure time ms/frame time ms/line interval us, width px / width offset px / height px / height offset px, sensor width px / sensor height px, trigger at bottom
- [ ] as written above, swap sensor width px / sensor height px to match order of width first then height second
- [ ] frame to ms should be indicator? setting it to a value raises error
- [ ] same for line interval us. although this one can be set for some cameras, but not for others...

how should we handle indicator vs controls which different between drivers within the same device class? line interval is only a property for the vieworks camera https://github.com/AllenNeuralDynamics/voxel/blob/6cee4f5bca5afcaf4e66681c9b7c0b040a57e0dd/voxel/devices/camera/vieworks_egrabber.py#L196 but can be set for the hamamatsu camera https://github.com/AllenNeuralDynamics/voxel/blob/6cee4f5bca5afcaf4e66681c9b7c0b040a57e0dd/voxel/devices/camera/hamamatsu_dcam.py#L221

**Comment by micahwoodard** [comment]
> this looks great, very minor tweaks
> 
> * [ ]  restack the horizontal sections as live/snapshot, binning/pixel type, exposure time ms/frame time ms/line interval us, width px / width offset px / height px / height offset px, sensor width px / sensor height px, trigger at bottom
> * [ ]  as written above, swap sensor width px / sensor height px to match order of width first then height second
> * [ ]  frame to ms should be indicator? setting it to a value raises error
> * [ ]  same for line interval us. although this one can be set for some cameras, but not for others...
> 
> how should we handle indicator vs controls which different between drivers within the same device class? line interval is only a property for the vieworks camera https://github.com/AllenNeuralDynamics/voxel/blob/6cee4f5bca5afcaf4e66681c9b7c0b040a57e0dd/voxel/devices/camera/vieworks_egrabber.py#L196 but can be set for the hamamatsu camera https://github.com/AllenNeuralDynamics/voxel/blob/6cee4f5bca5afcaf4e66681c9b7c0b040a57e0dd/voxel/devices/camera/hamamatsu_dcam.py#L221

It should all be taken care of by the fact that they don't have setters if I'm understanding your question correctly. It's a bug that the FrameTime isn't being disabled so I'm checking that out now

**Comment by micahwoodard** [comment]
Okay should be fixed now

**Comment by adamkglaser** [comment]
OK to merge this after digging into https://github.com/AllenNeuralDynamics/view/issues/31. Can also merge this and then do a new PR for https://github.com/AllenNeuralDynamics/view/issues/31.

**Pull request merged**
