### PR TITLE
Feat voxel 41 live update descriptor

### PR DESCRIPTION
**Pull request by micahwoodard**
- removes locks since this is now handled by voxel
- expects device properties that need updating to be in gui config
- expects operation properties that need updating to be in gui config
- handles workers that are polling device and operation properties

### CODE REVIEW

**Comment by adamkglaser** [comment]
@micahwoodard  this looks great. Do you have an example of what the progress bar you added looks like? Where does this widget get placed, into the parent widget of that operation or device, or do they all get collected into a widget displaying all progress bars?

**Comment by micahwoodard** [comment]
@adamkglaser I added in functionality for being able to livestream during an acquisition by adding in a latest_frame property in the voxel camera drivers. 

Here is what the progress bars look like right now. The progress bars replace the text boxes within the parent widgets. As you can see in the video, the progress property doesn't look like it's being updated properly in the imaris and robocoby driver but the widget functionality is working as it's just polling what the progress is. We can move the progress bars to their own widget and maybe also tackle how best to display the progress of the acquisition as a whole?


https://github.com/user-attachments/assets/a4cd4ccc-328a-48d0-acfa-73accc56ae74

**Comment by adamkglaser** [comment]
This looks great, and yeah we can think about a combined widget for all of these "signals" - almost like a resource monitor type of thing for the instrument. But not strictly a priority now, having them embedded like you show in the video is great.

I might have missed it, but they aren't updating properly because of some bug in either the driver or the widget? Or is it just that the test you did in the video capture didn't actually run a scan?

**Comment by adamkglaser** [comment]
@micahwoodard I am now remembering... the progress in the writer classes is something that I never finished. If you like in https://github.com/AllenNeuralDynamics/voxel/blob/develop/voxel/writers/imaris.py

```self.progress``` is initialized as 0 and then never updated. This is because I never took the time to figure out how to share a value out of the ```_run()``` Process. I know it is doable, I think using a shared value from the multiprocessing library. But basically the progress has to be calculated within ```_run()```, updating the ```self.progress``` attribute of the writer class.

**Comment by micahwoodard** [comment]
> @micahwoodard this looks great, and yeah we can think about a combined widget for all of these "signals" - almost like a resource monitor type of thing for the instrument. But not strictly a priority now, having them embedded like you show in the video is great.
> 
> I might have missed it, but they aren't updating properly because of some bug in either the driver or the widget? Or is it just that the test you did in the video capture didn't actually run a scan?

Yeah they aren't updating properly because of a bug in the drivers. The widgets are just polling the value of the property and updating the widget so as long as the driver is correctly updating, the widget will be correct

**Comment by adamkglaser** [comment]
@micahwoodard I fixed the drivers in Voxel so this should be working now. OK to merge with me.

**Review by adamkglaser — APPROVED** [review]

**Comment by micahwoodard** [comment]
Oh great thanks let me get the pull request in voxel squared away and then we can merge in later today

**Pull request merged**
